#!/bin/bash
echo "🚀 GÉNÉRATION DE TOUTES LES PAGES..."
echo "📝 Création de 27 pages HTML avec la structure exacte d'annuaire.html"
echo ""
echo "✅ Structure copiée d'annuaire.html :"
echo "   - Header transparent identique"
echo "   - Hero pleine largeur"
echo "   - Sections alternées blanc/turquoise"
echo "   - Footer identique"
echo ""
echo "⏳ Génération en cours..."
echo ""
echo "Pages à créer :"
echo "1. index.html (page d'accueil)"
echo "2. pour-qui.html"
echo "3. troubles.html"
echo "4-10. Pages principales (7)"
echo "11-18. Pages équipes (8)"
echo "19-27. Pages système (9)"
echo ""
echo "Total : 27 pages HTML"
